
name = "DashTreeComponents"
uuid = "1b08a953-4be3-4667-9a23-9cd2a9d78771"
authors = ["Wouter Wakker <wouter.wakker@outlook.com>"]
version = "0.0.2"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
